gc_second = 30
SocketPort = 2022
WebSocketPort = 2080
send_second = 5
pass = "3x"
[wss]
  crt = "/etc/pki/tls/certs/ws.fruitsadventures.com/nginx.crt"
  key = "/etc/pki/tls/certs/ws.fruitsadventures.com/private.key"
#   port = 2082
  
[test]
  test1 = "123 A Street"
  test2 = "AnyVille"
  "email address" = "newvfhhu@yahoo.com.tw"

